/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Core.Cache_Reader;
import Core.Log;
import Core.Presant_Validation;
import Core.User_Validation;
import java.awt.Color;

/**
 *
 * @author Jayashanka Deshan
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
        Log.add_Log("A");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        roundPanel15 = new com.deshan.swing.RoundPanel();
        jTextField8 = new javax.swing.JTextField();
        time_zone = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        today = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundPanel15.setBackground(new java.awt.Color(255, 255, 255));

        jTextField8.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(102, 102, 102));
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("SCAN YOUR CARD HERE");
        jTextField8.setBorder(null);
        jTextField8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField8FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField8FocusLost(evt);
            }
        });
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout roundPanel15Layout = new javax.swing.GroupLayout(roundPanel15);
        roundPanel15.setLayout(roundPanel15Layout);
        roundPanel15Layout.setHorizontalGroup(
            roundPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundPanel15Layout.setVerticalGroup(
            roundPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(roundPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 450, 390, -1));

        time_zone.setFont(new java.awt.Font("Yu Gothic", 1, 48)); // NOI18N
        time_zone.setForeground(new java.awt.Color(102, 102, 102));
        time_zone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time_zone.setText("10:45 P.M");
        jPanel1.add(time_zone, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 800, 50));

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ICEBURG ACCESS CONTROL");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 800, 40));

        today.setFont(new java.awt.Font("Monospaced", 1, 20)); // NOI18N
        today.setForeground(new java.awt.Color(102, 102, 102));
        today.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        today.setText("2010.12.22");
        jPanel1.add(today, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 800, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/main.gif"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField8FocusGained

        if(jTextField8.getText().equals("SCAN YOUR CARD HERE"))
        {
            jTextField8.setText("");

            jTextField8.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_jTextField8FocusGained

    private void jTextField8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField8FocusLost

        if(jTextField8.getText().equals(""))
        {
            jTextField8.setText("SCAN YOUR CARD HERE");

            jTextField8.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_jTextField8FocusLost

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased

        if(jTextField8.getText().length() == 10)
        {
            if(jTextField8.getText().equals(Cache_Reader.reader("Master_Card.key")))
            {
                Log.add_Log("D");

                Notification panel = new Notification(this, Notification.Type.SUCCESS, Notification.Location.BOTTOM_CENTER, "System Will Exit In 5 Seconds");

                panel.showNotification();

                exit();
            }
            else
            {
                int data = User_Validation.validation_userID(jTextField8.getText());

                if(data == 1)
                {
                    int val = Presant_Validation.validation_userID(jTextField8.getText());
                    
                    if(val == 1)
                    {
                        Notification panel = new Notification(this, Notification.Type.SUCCESS, Notification.Location.BOTTOM_CENTER, "ACCESS GRENTED");

                        panel.showNotification();

                        jTextField8.setText("");
                    }
                    else
                    {
                        Notification panel = new Notification(this, Notification.Type.WARNING, Notification.Location.BOTTOM_CENTER, "Unauthorized Access Detected");

                        panel.showNotification();

                        jTextField8.setText("");
                    }
                }
                else
                {
                    Notification panel = new Notification(this, Notification.Type.WARNING, Notification.Location.BOTTOM_CENTER, "That Card Seems Not Registerd Yet");

                    panel.showNotification();

                    jTextField8.setText("");
                }
            }
        }
    }//GEN-LAST:event_jTextField8KeyReleased

    
    public void exit()
    {
        new java.util.Timer().schedule( 
        new java.util.TimerTask()
        {
            @Override
        
            public void run() 
            {
                System.exit(0);
            }
        }, 
        5000 
        );
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField jTextField8;
    private com.deshan.swing.RoundPanel roundPanel15;
    private javax.swing.JLabel time_zone;
    private javax.swing.JLabel today;
    // End of variables declaration//GEN-END:variables
}
