/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Core.Cache_Reader;
import Core.Connector;
import Core.Log;
import Core.Presant_Validation;
import Core.User_Validation;
import Core.get_localDate;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *
 * @author Jayashanka Deshan
 */
public class Home extends javax.swing.JFrame {

    Integer value;
    
    String condition = null;
     
    public Home() {
        initComponents();
        
        Timer timer;
        
        ActionListener actionListener = new ActionListener() 
        {
            @Override
            public void actionPerformed(ActionEvent e) 
            {
                Date date = new Date();
                
                DateFormat timeFormat = new SimpleDateFormat("hh:mm:ss a");
                
                String time = timeFormat.format(date);
                
                timeFormat = new SimpleDateFormat("dd MMMM yyyy");
                
                DateFormat get_status = new SimpleDateFormat("HH");
                
                String status = get_status.format(date);
                
                value = Integer.valueOf(status);
                
                 if((value>=00)&&(value<13))
                {                    
                    condition = "MORNING";
                }
                if((value>=13)&&(value<18))
                {
                    condition = "EVENING";
                }
                if((value>=18)&&(value<=24))
                {
                    condition = "NIGHT";
                }
                
                time_zone.setText(time);
                
                today.setText(timeFormat.format(date)+" | "+condition);
                
            }
        };
        
        timer = new Timer(1000, actionListener);
        
        timer.setInitialDelay(0);
        
        timer.start();
        
        tab.setSelectedIndex(0);
        
        Log.add_Log("A");
       
    }
    
    public void tasker()
    {
        new java.util.Timer().schedule( 
        new java.util.TimerTask() {
            @Override
            public void run() 
            {
                tab.setSelectedIndex(0);
                
                jTextField8.setText("SCAN YOUR CARD HERE");
            }
        }, 
        3000 
        );
    }
    
    
    public void exit()
    {
        new java.util.Timer().schedule( 
        new java.util.TimerTask()
        {
            @Override
        
            public void run() 
            {
                System.exit(0);
            }
        }, 
        5000 
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab = new tabbed.MaterialTabbed();
        jPanel1 = new javax.swing.JPanel();
        today = new javax.swing.JLabel();
        time_zone = new javax.swing.JLabel();
        roundPanel15 = new com.deshan.swing.RoundPanel();
        jTextField8 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        roundPanel16 = new com.deshan.swing.RoundPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tab.setBackground(new java.awt.Color(255, 255, 255));
        tab.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        tab.setEnabled(false);
        tab.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        today.setFont(new java.awt.Font("Monospaced", 1, 20)); // NOI18N
        today.setForeground(new java.awt.Color(102, 102, 102));
        today.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        today.setText("2010.12.22");
        jPanel1.add(today, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 770, 30));

        time_zone.setFont(new java.awt.Font("Yu Gothic", 1, 48)); // NOI18N
        time_zone.setForeground(new java.awt.Color(102, 102, 102));
        time_zone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time_zone.setText("10:45 P.M");
        jPanel1.add(time_zone, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 770, 50));

        roundPanel15.setBackground(new java.awt.Color(255, 255, 255));

        jTextField8.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(102, 102, 102));
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("SCAN YOUR CARD HERE");
        jTextField8.setBorder(null);
        jTextField8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField8FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField8FocusLost(evt);
            }
        });
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout roundPanel15Layout = new javax.swing.GroupLayout(roundPanel15);
        roundPanel15.setLayout(roundPanel15Layout);
        roundPanel15Layout.setHorizontalGroup(
            roundPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundPanel15Layout.setVerticalGroup(
            roundPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(roundPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 450, 390, -1));

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ICEBURG ATTENDANCE SYSTEM");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 750, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/main.gif"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 600));

        tab.addTab("ADD EMPLOYER", jPanel1);

        jPanel2.setBackground(new java.awt.Color(242, 242, 242));
        jPanel2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        roundPanel16.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/check-circle.gif"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GOOD MORNING MISTER SHANKER HAVE A NICE DAY !");

        javax.swing.GroupLayout roundPanel16Layout = new javax.swing.GroupLayout(roundPanel16);
        roundPanel16.setLayout(roundPanel16Layout);
        roundPanel16Layout.setHorizontalGroup(
            roundPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(roundPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundPanel16Layout.setVerticalGroup(
            roundPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel16Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel4)
                .addGap(56, 56, 56)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tab.addTab("EMPLOYER PROFILES", jPanel2);

        getContentPane().add(tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField8FocusGained

        if(jTextField8.getText().equals("SCAN YOUR CARD HERE"))
        {
            jTextField8.setText("");

            jTextField8.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_jTextField8FocusGained

    private void jTextField8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField8FocusLost

        if(jTextField8.getText().equals(""))
        {
            jTextField8.setText("SCAN YOUR CARD HERE");

            jTextField8.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_jTextField8FocusLost

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
        
        if(jTextField8.getText().length() == 10)
        {
            if(jTextField8.getText().equals(Cache_Reader.reader("Master_Card.key")))
            {
                Log.add_Log("D");
                
                Notification panel = new Notification(this, Notification.Type.SUCCESS, Notification.Location.TOP_CENTER, "System Will Exit In 5 Seconds");
        
                panel.showNotification();
                
                exit();
            }
            else
            {
                int data = User_Validation.validation_userID(jTextField8.getText());
                
                if(data == 1)
                {
                    int val = Presant_Validation.validation_userID(jTextField8.getText());
                    
                    if(val == 1)
                    {
                        Notification panel = new Notification(this, Notification.Type.INFO, Notification.Location.TOP_CENTER, "Your Record Alrady Recorded Have a Nice Day!");
                    
                        panel.showNotification();
                        
                        jTextField8.setText("");
                    }
                    else
                    {
                        add_data();
                        
                        tab.setSelectedIndex(1);
                    
                        load_user(jTextField8.getText());
                    } 
                }
                else
                {
                    Notification panel = new Notification(this, Notification.Type.WARNING, Notification.Location.TOP_CENTER, "That Card Seems Not Registerd Yet");
                    
                    panel.showNotification();
                    
                    jTextField8.setText("");
                }
            }
        }

    }//GEN-LAST:event_jTextField8KeyReleased

    public void load_user(String id)
    {
        
        String SQL = "SELECT * FROM employee where emp_id = "+id+";";
        
        Connection connection = Connector.connection();
        
        try
        {
            Statement stmt = connection.createStatement();
            
            ResultSet rs = stmt.executeQuery(SQL);
            
            while(rs.next())
            {
                jLabel1.setText("GOOD "+condition+" "+rs.getString("emp_name").toUpperCase()+", HAVE A NICE DAY!");
            }
            
            tasker();
        }
        catch(Exception ERROR)
        {
            System.out.println(ERROR);
        }          
    }
    
    public static void add_data()
    {
        Random rand = new Random();
        
        int random_id = rand.nextInt(99999);

        String ID = String.valueOf(random_id);
        
        String query = "INSERT INTO attendance VALUES ("+ID+",'P','"+get_localDate.Date()+"', '"+get_localDate.Time()+"', "+Integer.valueOf(jTextField8.getText())+");";
        
        System.out.println(query);
        
        Connection conn = Connector.connection();
        
       try
       {
           PreparedStatement preparedStatement = conn.prepareStatement(query);

           preparedStatement.executeUpdate();
                      
       }
       catch(Exception error)
       {
           System.out.println(error);
       }
    }    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JTextField jTextField8;
    private com.deshan.swing.RoundPanel roundPanel15;
    private com.deshan.swing.RoundPanel roundPanel16;
    private tabbed.MaterialTabbed tab;
    private javax.swing.JLabel time_zone;
    private javax.swing.JLabel today;
    // End of variables declaration//GEN-END:variables
}
